stages:
  - test
  - build
  - push

Go test:
  stage: test
  image: golang:1.13
  script:
    - go test ./...
  tags:
    - docker

Go build:
  stage: build
  image: golang:1.13
  artifacts:
    paths:
    - our-life-before-corona
    expire_in: 1 week
  script:
    - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o our-life-before-corona
  tags:
    - docker

Docker build & push to quay (branch):
  stage: push
  needs: ["Go build"]
  except:
  - master
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login quay.io -u $DOCKER_USER -p $DOCKER_PWD
    - docker build . -t quay.io/marcelmue/our-life-before-corona:$CI_COMMIT_SHA
    - docker push quay.io/marcelmue/our-life-before-corona:$CI_COMMIT_SHA
  tags:
    - docker
    - privileged

Docker build & push to quay (master):
  stage: push
  needs: ["Go build"]
  only:
  - master
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login quay.io -u $DOCKER_USER -p $DOCKER_PWD
    - docker build . -t quay.io/marcelmue/our-life-before-corona:latest
    - docker push quay.io/marcelmue/our-life-before-corona
  tags:
    - docker
    - privileged

Docker build & push to GitLab registry (branch):
  stage: push
  needs: ["Go build"]
  except:
  - master
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  tags:
    - docker
    - privileged

Docker build & push to GitLab registry (master):
  stage: push
  needs: ["Go build"]
  only:
  - master
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"
  tags:
    - docker
    - privileged
