name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -v .

    - uses: actions/upload-artifact@v1
      with:
        name: our-life-before-corona
        path: our-life-before-corona


  pushMaster:
    name: Docker Master
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'

    steps:
    - uses: actions/checkout@master

    - uses: actions/download-artifact@v1
      with:
        name: our-life-before-corona

    - name: Add permissions
      run: mv /home/runner/work/our-life-before-corona/our-life-before-corona/our-life-before-corona ./binfile
    - run: pwd
    - run: ls -la
    - run: rm -rf /home/runner/work/our-life-before-corona/our-life-before-corona/
    - run: mv ./binfile ./our-life-before-corona
    - run: chmod +0755 our-life-before-corona

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: marcelmue/our-life-before-corona
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest"
        dockerfile: Dockerfile
        registry: quay.io

  pushPR:
    name: Docker PR
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@master

    - uses: actions/download-artifact@v1
      with:
        name: our-life-before-corona

    - name: Add permissions
      run: mv /home/runner/work/our-life-before-corona/our-life-before-corona/our-life-before-corona ./binfile
    - run: pwd
    - run: ls -la
    - run: rm -rf /home/runner/work/our-life-before-corona/our-life-before-corona/
    - run: mv ./binfile ./our-life-before-corona
    - run: chmod +0755 our-life-before-corona

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: marcelmue/our-life-before-corona
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
        registry: quay.io

